USE [DBAUtility]
GO

INSERT INTO [EventData].[LongRunningQueries]
([EventName]
,[PackageName]
,[DatetimeStampUTC]
,[DatetimeStampLocal]
,[EventDate]
,[ClientAppName]
,[ClientHostname]
,[Duration]
,[CPU]
,[LogicalReads]
,[PhysicalReads]
,[Writes]
,[RowCount]
,[LastRowCount]
,[LineNumber]
,[Offset]
,[OffsetEnd]
,[DatabaseName]
,[NTUsername]
,[Username]
,[PlanHandle]
,[QueryHash]
,[QueryHashSigned]
,[SessionId]
,[Statement]
,[SQLText]
,[SessionName]
,[SessionFilePathName]
)
SELECT
--TOP (1000)
[event_name]
,[package_name]
,[utc_timestamp]
,CONVERT(DATETIME, CONVERT(DATETIMEOFFSET, ([utc_timestamp] at time zone 'UTC') AT TIME ZONE 'Pacific Standard Time')) DatetimeLocal
,CONVERT(CHAR(10), DATEADD(HOUR, -7,[utc_timestamp]), 121) AS EventDate
,[client_app_name]
,[client_hostname]
,[duration]
,[cpu]
,[logical_reads]
,[physical_reads]
,[writes]
,[row_count]
,[last_row_count]
,[line_number]
,[offset]
,[offset_end]
,[database_name]
,[nt_username]
,[username]
,[plan_handle]
,[query_hash]
,[query_hash_signed]
,[session_id]
,[statement]
,[sql_text]
,[SessionName]
,[SessionFilePathName]
FROM [DBAUtility].[EventDataETL].[LongRunningQueries]