CREATE DATABASE [DBAUtility]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBAUtility', FILENAME = N'D:\MSSQL\Data\DBAUtility.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB ), 
 FILEGROUP [SECONDARY] 
( NAME = N'DBAUtility1', FILENAME = N'D:\MSSQL\Data\DBAUtility1.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB ),
( NAME = N'DBAUtility2', FILENAME = N'D:\MSSQL\Data\DBAUtility2.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB ),
( NAME = N'DBAUtility3', FILENAME = N'D:\MSSQL\Data\DBAUtility3.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB ),
( NAME = N'DBAUtility4', FILENAME = N'D:\MSSQL\Data\DBAUtility4.ndf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBAUtility_log', FILENAME = N'L:\MSSQL\Log\DBAUtility_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DBAUtility] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [DBAUtility] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DBAUtility] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DBAUtility] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DBAUtility] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DBAUtility] SET ARITHABORT OFF 
GO
ALTER DATABASE [DBAUtility] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DBAUtility] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DBAUtility] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [DBAUtility] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DBAUtility] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DBAUtility] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DBAUtility] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DBAUtility] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DBAUtility] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DBAUtility] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DBAUtility] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DBAUtility] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DBAUtility] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DBAUtility] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DBAUtility] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DBAUtility] SET  READ_WRITE 
GO
ALTER DATABASE [DBAUtility] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DBAUtility] SET  MULTI_USER 
GO
ALTER DATABASE [DBAUtility] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DBAUtility] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DBAUtility] SET DELAYED_DURABILITY = DISABLED 
GO
USE [DBAUtility]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [DBAUtility]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'SECONDARY') ALTER DATABASE [DBAUtility] MODIFY FILEGROUP [SECONDARY] DEFAULT
GO
