IF EXISTS (
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = DB_NAME(DB_ID())
AND TABLE_SCHEMA = 'WSECU'
AND TABLE_NAME = 'batch_items'
AND COLUMN_NAME = 'batch_type'
AND DATA_TYPE = 'varchar'
)