:CONNECT OLY-OPCONSQL-01
GO

SELECT [OPCONXPS].[dbo].[JMASTER_AUX].[SKDID]
,[OPCONXPS].[dbo].[SNAME].SKDNAME
,[JOBNAME]
,[JAFC]
,[JASEQNO]
,[JAVALUE]
FROM [OPCONXPS].[dbo].[JMASTER_AUX] 
INNER JOIN [OPCONXPS].[dbo].[SNAME] ON JMASTER_AUX.SKDID=SNAME.SKDID
WHERE [OPCONXPS].[dbo].[JMASTER_AUX].JAVALUE LIKE '%dataservices%'
AND [OPCONXPS].[dbo].[SNAME].SKDNAME LIKE '%000-STMT%'

ORDER BY SKDNAME
GO